### ISSUE TITLE
基于真实世界的赛车游戏

### ISSUE THREAD

**Issue by simonmysun** [simonmysun/ToDoSet#52]

**Comment by hczhcz** [comment]
Mark.
Is this something like "Live For Speed" or "RFactor"?

**Comment by simonmysun** [comment]
啊.. 是我没表达清楚, 我指的是基于地图数据来做一个游戏, 赛车或者飞行或者什么的, 不过你说的游戏很好玩.... 玩到现在... 

http://cesiumjs.org/demos.html 我查了查已经有人实现过了.

**Comment by hczhcz** [comment]
喔这样……脑洞赞一个

**Comment by simonmysun** [comment]
^_^

**Comment by simonmysun** [comment]
@hczhcz 诶你是怎么找到这里的..?

**Comment by hczhcz** [comment]
以前某社交网站上看到过你，然后昨天看到[这个issue](https://github.com/iiordanov/remote-desktop-clients/issues/42)，就找到这里了

**Comment by simonmysun** [comment]
噢噢这样... 那个.. 那你是..? 我想不起来你在其他社交网络上的身份...

**Comment by simonmysun** [comment]
https://github.com/vizicities/vizicities 我想做到的效果大概是这个样子的. 也需不需要我做了吧
